### ISSUE TITLE
Populate netlify site with NZTC + signup content

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#48]
- [ ] Add icon to https://practical-gates-41c557.netlify.app for NZTC challenge
- [ ] Link NZTC challenge icon to something appropriate, eg. http://challenges.rangl.org/web/challenges/challenge-page/8/overview
- [ ] Add icon for signup to RangL mailing list
- [ ] Link signup icon to eg. http://challenges.rangl.org/web/challenges/challeng
- [ ] Change 'optimal power flow' to 'Generation scheduling' at https://practical-gates-41c557.netlify.app
- [ ] Link 'Generation scheduling' to eg. http://challenges.rangl.org/web/challenges/challenge-page/1/overview

**Comment by moriartyjm** [comment]
@jmontalvo94 the source for the documentation site can be found at

https://gitlab.com/rangl/sites/docs

**Comment by jmontalvo94** [comment]
There is a problem with Node.js version 17.0.0 to start the local development server. It seems to be related to LTS, downgrading to version 16.12.0 (LTS starting next week) fixes the issue. See [this stackoverflow issue on the topic](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported).

Error stack:

```
landing on  master via  v17.0.0 took 1m15s
❯ yarn start
yarn run v1.22.17
$ docusaurus start
Starting the development server...
Docusaurus website is running at "http://localhost:3000/".

● Client █████████████████████████ setup (9%) compilation
 FileUriPlugin

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/jorge/code/rangl/landing/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/home/jorge/code/rangl/landing/node_modules/webpack/lib/util/createHash.js:80:21)
    at /home/jorge/code/rangl/landing/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next33 (eval at create (/home/jorge/code/rangl/landing/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:57:1)
    at _next11 (eval at create (/home/jorge/code/rangl/landing/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:189:1)
    at Hook.eval [as call] (eval at create (/home/jorge/code/rangl/landing/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:239:1)
    at Hook.CALL_DELEGATE [as _call] (/home/jorge/code/rangl/landing/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/jorge/code/rangl/landing/node_modules/webpack/lib/Compiler.js:1053:26)
    at /home/jorge/code/rangl/landing/node_modules/webpack/lib/Compiler.js:1097:29
    at Hook.eval [as callAsync] (eval at create (/home/jorge/code/rangl/landing/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/jorge/code/rangl/landing/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/jorge/code/rangl/landing/node_modules/webpack/lib/Compiler.js:1092:28)
    at /home/jorge/code/rangl/landing/node_modules/webpack/lib/Watching.js:200:19
    at Hook.eval [as callAsync] (eval at create (/home/jorge/code/rangl/landing/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

landing on  master via  v17.0.0 took 5s
❯ nvm use 16
Now using node v16.12.0 (npm v8.1.0)

landing on  master via  v16.12.0
❯ yarn start
yarn run v1.22.17
$ docusaurus start
Starting the development server...
Docusaurus website is running at "http://localhost:3000/".

✔ Client
  Compiled successfully in 1.09m

ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/jorge/code/rangl/landing
ℹ ｢wds｣: 404s will fallback to /index.html
```
